packages:
  - apps/*

catalog:
  '@antfu/eslint-config': ^5.3.0
  '@types/cors': ^2.8.17
  '@types/express': ^4.17.21
  '@types/fluent-ffmpeg': ^2.1.26
  '@types/node': ^24.5.2
  '@typescript/native-preview': 7.0.0-dev.20250822.1
  '@unocss/eslint-plugin': ^66.5.1
  '@unocss/preset-attributify': ^66.5.1
  '@unocss/preset-icons': ^66.5.1
  '@unocss/preset-uno': ^66.5.1
  '@unocss/reset': ^66.5.1
  '@unocss/transformer-directives': ^66.5.1
  '@unocss/transformer-variant-group': ^66.5.1
  '@vitejs/plugin-vue': ^6.0.1
  '@vue/compiler-sfc': ^3.5.21
  '@vueuse/core': ^13.9.0
  '@vueuse/head': ^2.0.0
  '@vueuse/router': ^13.9.0
  cors: ^2.8.5
  cross-env: ^10.1.0
  eslint: ^9.35.0
  express: ^4.18.2
  fluent-ffmpeg: ^2.1.3
  husky: ^9.1.7
  jsdom: ^27.0.0
  knip: ^5.63.1
  ky: ^1.10.0
  nx: ^21.5.2
  pinia: ^3.0.3
  prettier: ^3.6.2
  tsx: ^4.7.1
  typescript: ^5.9.2
  unocss: ^66.5.1
  unplugin-auto-import: ^20.1.0
  unplugin-vue-components: ^29.0.0
  vite: ^7.1.6
  vue: ^3.5.21
  vue-router: ^4.5.1
  vue-tsc: ^3.0.7

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - bcrypt
  - esbuild
  - nice-napi
  - nx
  - oxc-resolver
  - prisma
  - vue-demi
