name: Build and Deploy Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_REGISTRY_URL: git.nekatz.com
  DOCKER_IMAGE_NAME: ${{ gitea.repository }}
  DOCKER_IMAGE: ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_IMAGE_NAME }}
  HUSKY: 0

jobs:
  checks:
    name: Setup, Lint, TypeCheck, and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Lint, TypeCheck
        run: pnpm nx run-many --target=lint,typecheck --parallel

  docker-frontend:
    name: Build & Push Frontend Docker Image
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ gitea.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: frontend
          push: true
          tags: ${{ env.DOCKER_IMAGE }}-frontend:latest
          build-args: |
            VITE_BACKEND_URL=${{ vars.VITE_BACKEND_URL }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}-frontend:cache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}-frontend:cache,mode=max,image-manifest=true,oci-mediatypes=true

  docker-backend:
    name: Build & Push Backend Docker Image
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ gitea.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: backend
          push: true
          tags: ${{ env.DOCKER_IMAGE }}-backend:latest
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}-backend:cache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}-backend:cache,mode=max,image-manifest=true,oci-mediatypes=true
